allowBuilds:
  esbuild: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.3
  vitest: 4.1.11
  vite-plus: 0.3.3
  "@vitest/browser-playwright": 4.1.11
minimumReleaseAgeExclude:
  - "@sveltejs/kit@3.0.0"
  - "@sveltejs/adapter-auto@8.0.0"
  - "@sveltejs/adapter-cloudflare@8.0.0"
overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
